#! /bin/bash

if [ -f /Volumes/rdisk/ramdisk-id ]; then
    TDIR=$(mktemp -d /Volumes/rdisk/ad-test.XXXXXX)
else
    TDIR=$(mktemp -d -t XXXXXX)
fi
TESTDIR=$(dirname $0)

# ======================================================================

function on_exit
{
    rm -rf "$TDIR"
}

trap on_exit EXIT

function failed
{
    echo FAILED >&2
    exit 1
}

trap failed ERR

# ======================================================================

export LD_LIBRARY_PATH="${ACMACSD_ROOT}/lib:${LD_LIBRARY_PATH}"
cd "$TESTDIR"

#../bin/test-copy ./newick.json.xz "$TDIR"/tree.json.xz
#../bin/test-copy "$TDIR"/tree.json.xz "$TDIR"/tree2.json.xz
#xzdiff "$TDIR"/tree.json.xz "$TDIR"/tree2.json.xz

SETTINGS="$TDIR/tree.settings.json"
../dist/sigp --init-settings "$SETTINGS" ./newick.json.xz "$TDIR"/tree.pdf
../dist/sigp -s "$SETTINGS" ./newick.json.xz "$TDIR"/tree.pdf
