#! /bin/bash

TDIR=$(mktemp -d)
TESTDIR=$(dirname $0)

# ======================================================================

function on_exit
{
    rm -rf "$TDIR"
}

trap on_exit EXIT

function failed
{
    echo FAILED >&2
    exit 1
}

trap failed ERR

# ======================================================================

cd "$TESTDIR"
../bin/test-copy ./newick.json.xz "$TDIR"/tree.json.xz
../bin/test-copy "$TDIR"/tree.json.xz "$TDIR"/tree2.json.xz
xzdiff "$TDIR"/tree.json.xz "$TDIR"/tree2.json.xz
